name: 'Node Setup and Install'
description: 'Set up Node.js and install npm dependencies with caching'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  cache-dependency-path:
    description: 'Lockfile(s) for cache key'
    required: false
    default: '**/package-lock.json'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      run: npm ci
