name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-setup
        with: { node-version: '20' }
      - run: npm run lint
      - run: npm run format:check

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-setup
        with: { node-version: '20' }
      - name: Run tests (coverage >=80% enforced by Jest config)
        run: npm test
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with: { name: coverage, path: coverage }
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false     # flip to true after adding token for private repos
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-setup
        with: { node-version: '20' }
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with: { name: dist, path: dist }
